package com.universalrp.appforge.model

/**
 * Generates a complete Android Studio project from an [AppProject].
 *
 * The generated project wraps the same HTML app the preview shows in a WebView,
 * so the "app" you design in AppForge also exists as a real APK you can build
 * locally or on GitHub Actions. No compiler runs inside AppForge itself — it
 * writes sources, which is the only honest way to do this on a phone.
 */
object AndroidCodeGen {

    /** Files are returned as relative path -> file content. */
    fun generate(project: AppProject): Map<String, String> {
        val pkg = packageName(project)
        val files = LinkedHashMap<String, String>()

        files["settings.gradle.kts"] = settingsGradle(project)
        files["build.gradle.kts"] = rootGradle()
        files["gradle.properties"] = GRADLE_PROPERTIES
        files["app/build.gradle.kts"] = appGradle(pkg)
        files["app/src/main/AndroidManifest.xml"] = MANIFEST
        files["app/src/main/java/" + pkg.replace('.', '/') + "/MainActivity.kt"] = mainActivity(pkg)
        files["app/src/main/assets/index.html"] = HtmlRenderer.render(project)
        files["app/src/main/res/values/strings.xml"] = stringsXml(project)
        files["app/src/main/res/values/themes.xml"] = themesXml(project)
        files[".github/workflows/build-apk.yml"] = workflow(project)
        files["README.md"] = readme(project, pkg)
        return files
    }

    /** A safe Java package name derived from the app name. */
    fun packageName(project: AppProject): String {
        val slug = project.name.lowercase()
            .map { c -> if (c.isLetterOrDigit()) c else ' ' }
            .joinToString("")
            .split(' ')
            .filter { it.isNotBlank() }
            .joinToString("")
            .ifBlank { "myapp" }
        val safe = if (slug.first().isDigit()) "app$slug" else slug
        return "com.appforge.$safe"
    }

    // ------------------------------------------------------------------ parts

    private fun settingsGradle(project: AppProject): String {
        val rootName = project.name.replace("\"", "").ifBlank { "MiniApp" }
        return """
            pluginManagement {
                repositories {
                    google()
                    mavenCentral()
                    gradlePluginPortal()
                }
            }
            dependencyResolutionManagement {
                repositories {
                    google()
                    mavenCentral()
                }
            }
            rootProject.name = "$rootName"
            include(":app")
        """.trimIndent() + "\n"
    }

    private fun rootGradle(): String = """
        plugins {
            id("com.android.application") version "8.13.0" apply false
            id("org.jetbrains.kotlin.android") version "2.2.21" apply false
        }
    """.trimIndent() + "\n"

    private fun appGradle(pkg: String): String = """
        plugins {
            id("com.android.application")
            id("org.jetbrains.kotlin.android")
        }

        android {
            namespace = "$pkg"
            compileSdk = 36

            defaultConfig {
                applicationId = "$pkg"
                minSdk = 24
                targetSdk = 36
                versionCode = 1
                versionName = "1.0"
            }

            buildTypes {
                release {
                    isMinifyEnabled = false
                }
            }

            compileOptions {
                sourceCompatibility = JavaVersion.VERSION_17
                targetCompatibility = JavaVersion.VERSION_17
            }

            kotlin {
                compilerOptions {
                    jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17)
                }
            }
        }

        dependencies {
            implementation("androidx.core:core-ktx:1.15.0")
            implementation("androidx.activity:activity-ktx:1.10.1")
        }
    """.trimIndent() + "\n"

    private fun mainActivity(pkg: String): String = """
        package $pkg

        import android.annotation.SuppressLint
        import android.os.Bundle
        import android.webkit.WebView
        import androidx.activity.ComponentActivity

        /**
         * Generated by AppForge. The whole app is a single offline HTML file in
         * assets, loaded with an https base URL so localStorage (saved text and
         * ticks) persists between launches.
         */
        class MainActivity : ComponentActivity() {

            private lateinit var web: WebView

            @SuppressLint("SetJavaScriptEnabled")
            override fun onCreate(savedInstanceState: Bundle?) {
                super.onCreate(savedInstanceState)
                web = WebView(this)
                web.settings.javaScriptEnabled = true
                web.settings.domStorageEnabled = true
                val html = assets.open("index.html").bufferedReader().use { it.readText() }
                web.loadDataWithBaseURL("https://appforge.local/", html, "text/html", "utf-8", null)
                setContentView(web)
            }
        }
    """.trimIndent() + "\n"

    private fun stringsXml(project: AppProject): String {
        val name = project.name
            .replace("&", "and")
            .replace("<", "")
            .replace(">", "")
            .ifBlank { "My App" }
        return """
            <?xml version="1.0" encoding="utf-8"?>
            <resources>
                <string name="app_name">$name</string>
            </resources>
        """.trimIndent() + "\n"
    }

    private fun themesXml(project: AppProject): String {
        val accent = project.accent.ifBlank { "#22D3EE" }
        return """
            <?xml version="1.0" encoding="utf-8"?>
            <resources>
                <color name="app_bg">#0B0F1E</color>

                <style name="Theme.MiniApp" parent="android:Theme.Material.NoActionBar">
                    <item name="android:windowBackground">@color/app_bg</item>
                    <item name="android:statusBarColor">$accent</item>
                </style>
            </resources>
        """.trimIndent() + "\n"
    }

    private fun workflow(project: AppProject): String {
        val appName = project.name.ifBlank { "Mini app" }
        return """
            # Builds the $appName APK in the cloud, for free.
            name: Build APK

            on:
              push:
                branches: [ main ]
              workflow_dispatch:

            jobs:
              build:
                runs-on: ubuntu-latest
                steps:
                  - uses: actions/checkout@v4

                  - uses: actions/setup-java@v4
                    with:
                      distribution: temurin
                      java-version: '17'

                  - uses: gradle/actions/setup-gradle@v4
                    with:
                      gradle-version: "8.14.3"

                  - name: Generate Gradle wrapper
                    run: gradle wrapper --gradle-version 8.14.3

                  - name: Build debug APK
                    run: gradle assembleDebug --no-daemon

                  - uses: actions/upload-artifact@v4
                    with:
                      name: app-apk
                      path: app/build/outputs/apk/debug/*.apk
        """.trimIndent() + "\n"
    }

    private fun readme(project: AppProject, pkg: String): String {
        val description = project.description.ifBlank { "An app designed with AppForge." }
        return """
            # ${project.name}

            $description

            Generated by **AppForge** (offline app builder). The app is one
            self-contained HTML file wrapped in a WebView, so it works with no server
            and no internet connection. Text fields and checklists are stored locally
            on the device.

            ## Build the APK

            **Easy way (no PC):** upload this folder to a new GitHub repository, then open
            *Actions → Build APK → Run workflow*. When it finishes, download the
            `app-apk` artifact and install it on your phone (allow "install unknown apps").

            **Local way:** open the folder in Android Studio and press Run, or:

            ```bash
            gradle wrapper          # once
            ./gradlew assembleDebug
            # APK: app/build/outputs/apk/debug/app-debug.apk
            ```

            ## Editing your app

            Open AppForge again, edit this project and export a fresh copy — the HTML
            inside `assets/index.html` is the only file that really changes.

            - Package name: `$pkg`
            - Screens: ${project.screens.size}
        """.trimIndent() + "\n"
    }

    private val MANIFEST = """
        <?xml version="1.0" encoding="utf-8"?>
        <manifest xmlns:android="http://schemas.android.com/apk/res/android">

            <application
                android:allowBackup="true"
                android:label="@string/app_name"
                android:supportsRtl="true"
                android:theme="@style/Theme.MiniApp">

                <activity
                    android:name=".MainActivity"
                    android:exported="true">
                    <intent-filter>
                        <action android:name="android.intent.action.MAIN" />
                        <category android:name="android.intent.category.LAUNCHER" />
                    </intent-filter>
                </activity>
            </application>
        </manifest>
    """.trimIndent() + "\n"

    private val GRADLE_PROPERTIES = """
        android.useAndroidX=true
        kotlin.code.style=official
        org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8
    """.trimIndent() + "\n"
}
